### PR TITLE
add resizeable rows, ignore empty cnt files and fix cnt entries with …

### PR DESCRIPTION
**Pull request by cracyc**
…escaped equal sign

the resizing only works with win8+

### CODE REVIEW

**Comment by ArguaBILL** [comment]
it's interesting that it only failed on the unrecommended build

**Comment by cracyc** [comment]
Mingw tom.h header isn't complete.  The header can be generated from the idl but I don't know enough about cmake to do it right now.

**Comment by otya128** [comment]
image

**Comment by cracyc** [comment]
I tried https://docs.microsoft.com/en-us/windows/win32/api/tom/nf-tom-itextrow-setheight with 0 to fix the vertical spacing but it didn't work.  There doesn't seem to be an obvious way to tell whether the text will wrap or not.

**Pull request merged**
