### PR TITLE
set ime window hinstance to 0

### PR DESCRIPTION
**Pull request by cracyc**
fixes midi in magic school bus - human body
I did a small amount of IME testing and didn't see any problems but if there's problems an alternative is to hide the ime window from enumwindows.

### CODE REVIEW

**Comment by cracyc** [comment]
The build failure appears to be a glitch with appveyor because the error isn't with the compile.

**Comment by otya128** [comment]
Is this to make GetWindowWord16(hwnd, GWW_HINSTANCE) return 0?

**Comment by cracyc** [comment]
For that specific window, yes.  The program starts a second task which creates a windows.  The first task then enumerates all the windows in the system looking for the task hinstance.  It expects to find one but it finds two instead which breaks the logic.

**Comment by otya128** [comment]
Indeed, the HINSTANCE of the Default IME window seems to set the values of other windows.

**Pull request merged**
