### PR TITLE
switch to msftedit for rtf embedded links, better tables and better h…

### PR DESCRIPTION
**Pull request by cracyc**
…lines

Also fix popups that get recursively narrower until the window is one word wide and the popup background color

### CODE REVIEW

**Comment by otya128** [comment]
This seems to improve the rendering of the help file, but the link in the popup seems to stop working.

**Comment by cracyc** [comment]
I haven't found a help file with a link in the popup, although I tried to account for the possibility.  Do you have a link to one?

**Comment by otya128** [comment]
[This help file](https://www.digitalpad.co.jp/~takechin/archives/susie029.lzh) contains it. ( https://www.digitalpad.co.jp/~takechin/download.html )

I think WINHELP_CheckPopup processed the WM_LBUTTONDOWN message before processing EN_LINK.
image
image

**Comment by otya128** [comment]
It works!

**Pull request merged**
