### PR TITLE
force a redraw of the window frame when the theme is set

### PR DESCRIPTION
**Pull request by cracyc**
fixes https://github.com/otya128/winevdm/issues/452

### CODE REVIEW

**Comment by Anixx** [comment]
Are you sure you should redraw when the theme is set rather than otherwise? The issue happens on my system when there is no theme. This commit does not change anything.

**Comment by cracyc** [comment]
On my computer with Windows 10 I had the same problem with the same programs as you when aero is disabled, when enabled it works fine.  In my testing on Windows 7 with dwm disabled the problem doesn't occur, I don't have any way right now to test with dwm enabled.  All of this also applies to the caption problem.   This commit fixes it for me and the other commit fixes the captions.  It might be useful to know more about your specific hardware and software configuration but if I can't reproduce it then it won't be of very much help.

**Comment by Anixx** [comment]
Maybe you should use IsThemeActive for detecting if the host system themed which was used in this commit and works: https://github.com/otya128/winevdm/pull/544/commits/52a3d8fe6791ea82b9793a57dd2cae24bb54345c

**Comment by Anixx** [comment]
Maybe you should use IsThemeActive for detecting if the host system themed which was used in this commit and works: https://github.com/otya128/winevdm/commit/4f9172f4d1cd9483ed66bb0bfdd1a2bd4b74026d

**Pull request merged**
